[ACE1pack_test_files]
git-tree-sha1 = "9239bef3bf078cdb7804bbe929d521538669ba10"
lazy = true

    [[ACE1pack_test_files.download]]
    sha256 = "77fbb071ddb8a9068a3fddc0148a4a3e50acbc79d013638fc6759f9e91ee8d07"
    url = "https://github.com/gelzinyte/test_julia_artifacts/blob/main/ACE1pack_test_files.zip?raw=true"

[TiAl_tiny_dataset]
git-tree-sha1 = "4ed1c6b17027b0be0adabb73604d478364428a89"
lazy = true

    [[TiAl_tiny_dataset.download]]
    sha256 = "536cbc7c40225b4c536a852fadc26c1b29c1f2aa9fd8031d4152d2d053975254"
    url = "https://github.com/gelzinyte/test_julia_artifacts/blob/main/TiAl_tiny.zip?raw=true"
