[ACE1pack_test_files]
git-tree-sha1 = "6b47b035f06e56fa0ca5cd9b0fb976b7f03bd3ba"
lazy = true

    [[ACE1pack_test_files.download]]
    sha256 = "5416b14aa2356ce8a399102a45232e8c44e746c3270c4baa15d4bbcce9fcc2e7"
    url = "https://github.com/ACEsuit/ACEData/blob/master/tests/ACE1pack_test_files.tar.gz?raw=true"

[TiAl_tiny_dataset]
git-tree-sha1 = "86fd99369720539181edb3f27e0a265ae0c696df"
lazy = true

    [[TiAl_tiny_dataset.download]]
    sha256 = "3b286227cbd705a7d6f1a695c2decacda9981be588bcc5ce288e479f9e60db5e"
    url = "https://github.com/ACEsuit/ACEData/blob/master/trainingsets/TiAl_tiny.tar.gz?raw=true"
