[ACE1pack_test_files]
git-tree-sha1 = "59d62542a3be4f6b8b08bb9fe92048b13b044391"
lazy = true

    [[ACE1pack_test_files.download]]
    sha256 = "3ffe32a0e3cbae8836512c388f4e397f979031ba2d3ad92671755d4ad3417d69"
    url = "https://github.com/gelzinyte/test_julia_artifacts/blob/main/ACE1pack_test_files.zip?raw=true"

[TiAl_tiny_dataset]
git-tree-sha1 = "4ed1c6b17027b0be0adabb73604d478364428a89"
lazy = true

    [[TiAl_tiny_dataset.download]]
    sha256 = "3b0d8e1a853e0623e32894d400614d6ce5ac81e53ba6e4b39b68bfb86aba9750"
    url = "https://github.com/gelzinyte/test_julia_artifacts/blob/main/TiAl_tiny.zip?raw=true"
